"""Quiz questions for the 53 roadmap topics the original seed (quiz_seed.py) never covered:
all 41 quantum-machine-learning topics plus the 6 quantum-maths and 6 quantum-physics
foundations, plus 6 core topics whose only questions were non-multiple-choice.
Without them, sprint quizzes and per-topic practice quizzes for those topics
had nothing to draw from ("No quiz questions exist yet for this sprint's topics").

Three multiple-choice questions per topic, in the exact document shape quiz_seed.py uses.
The correct option is always stored first as opt_a; routers/quiz.py shuffles options every
time a quiz is started, so the stored order never reaches the learner.

Appended to SEED_QUESTIONS at the bottom of quiz_seed.py, so they are upserted on the next
backend start like every other seeded question.
"""
from typing import Any, Dict, List, Sequence, Tuple

# (concept, difficulty, prompt, correct answer, three distractors, explanation)
Question = Tuple[str, str, str, str, Sequence[str], str]


def _mcq(slug: str, domain_tag: str, question: Question) -> Dict[str, Any]:
    concept, difficulty, prompt, correct, wrong, explanation = question
    assert len(wrong) == 3, f"{slug}: needs exactly 3 distractors"
    options = [{"id": "opt_a", "text": correct}] + [
        {"id": f"opt_{letter}", "text": text} for letter, text in zip("bcd", wrong)
    ]
    return {
        "type": "mcq",
        "topic_slug": slug,
        "concept": concept,
        "difficulty": difficulty,
        "tags": [slug, domain_tag],
        "prompt": prompt,
        "options": options,
        "correct_answer": "opt_a",
        "explanation": explanation,
        "xp_reward": 10,
        "time_limit_seconds": 45,
    }


QUESTIONS_BY_TOPIC: Dict[str, Tuple[str, List[Question]]] = {
    # ------------------------------------------------------------------ maths
    "maths-vector-spaces": ("quantum-maths", [
        ("State space dimension", "easy",
         "What is the dimension of the state space of a single qubit?",
         "2 — a two-dimensional complex vector space",
         ["1", "4", "Infinite"],
         "A qubit's state is a combination of |0⟩ and |1⟩, so it lives in the 2-dimensional complex space ℂ²."),
        ("Linear independence", "medium",
         "A set of vectors is linearly independent when…",
         "No vector in the set can be written as a linear combination of the others",
         ["Every vector has unit length", "Every pair of vectors is orthogonal", "The vectors span the whole space"],
         "Independence only forbids one vector being built from the rest. Orthogonal sets are independent, but independent sets need not be orthogonal."),
        ("Multi-qubit dimension", "medium",
         "How many complex dimensions does the state space of n qubits have?",
         "2ⁿ",
         ["2n", "n²", "n"],
         "Each added qubit doubles the number of basis states, so n qubits need 2ⁿ complex amplitudes."),
    ]),
    "maths-dirac-bra-ket": ("quantum-maths", [
        ("Bra vectors", "easy",
         "In Dirac notation, what does the bra ⟨ψ| represent?",
         "The conjugate transpose (dual vector) of the ket |ψ⟩",
         ["The same column vector as |ψ⟩", "The complex conjugate of |ψ⟩ without transposing", "The probability of measuring ψ"],
         "A bra is the dual of a ket: transpose the column vector into a row and complex-conjugate every entry."),
        ("Normalisation", "medium",
         "If |ψ⟩ = α|0⟩ + β|1⟩ is normalised, which condition must hold?",
         "|α|² + |β|² = 1",
         ["α + β = 1", "α² + β² = 1, even for complex α and β", "|α| + |β| = 1"],
         "Normalisation means ⟨ψ|ψ⟩ = 1, and ⟨ψ|ψ⟩ = |α|² + |β|². Squaring complex numbers without the modulus is not enough."),
        ("Amplitude projection", "medium",
         "For |ψ⟩ = α|0⟩ + β|1⟩, what is ⟨0|ψ⟩?",
         "α, the probability amplitude of |0⟩",
         ["|α|²", "β", "1"],
         "Projecting onto ⟨0| picks out the coefficient of |0⟩. Its squared modulus |α|² is the probability, not the amplitude itself."),
    ]),
    "maths-inner-products": ("quantum-maths", [
        ("Orthogonality", "easy",
         "Two states |φ⟩ and |ψ⟩ are orthogonal when…",
         "⟨φ|ψ⟩ = 0",
         ["⟨φ|ψ⟩ = 1", "|φ⟩ = −|ψ⟩", "They have different norms"],
         "Orthogonal states have zero overlap, which is why a measurement can distinguish them perfectly."),
        ("Vector norm", "medium",
         "What is the norm of a vector |ψ⟩?",
         "√⟨ψ|ψ⟩",
         ["⟨ψ|ψ⟩²", "The sum of its components", "Its largest component"],
         "The norm is the square root of the inner product of the vector with itself."),
        ("Cauchy–Schwarz inequality", "hard",
         "The Cauchy–Schwarz inequality states that…",
         "|⟨φ|ψ⟩|² ≤ ⟨φ|φ⟩⟨ψ|ψ⟩",
         ["|⟨φ|ψ⟩| ≥ ⟨φ|φ⟩⟨ψ|ψ⟩", "⟨φ|ψ⟩ = ⟨ψ|φ⟩ always", "|⟨φ|ψ⟩|² = 1 for any two unit vectors"],
         "The overlap of two vectors can never exceed the product of their lengths. For unit vectors this means |⟨φ|ψ⟩|² ≤ 1."),
    ]),
    "maths-matrices-operators": ("quantum-maths", [
        ("Unitary operators", "easy",
         "Which property defines a unitary operator U?",
         "U†U = I",
         ["U = U†", "U² = 0", "det(U) = 0"],
         "Unitary operators preserve the norm of every state, which is exactly the condition U†U = I."),
        ("Hermitian observables", "medium",
         "Why are observables represented by Hermitian operators?",
         "Hermitian operators have real eigenvalues, matching real measurement outcomes",
         ["They are always invertible", "They preserve the norm of every state", "They commute with every other operator"],
         "Measured values are real numbers, and Hermitian operators (H = H†) are guaranteed to have real eigenvalues."),
        ("Spectral decomposition", "hard",
         "The spectral decomposition of a Hermitian operator H writes it as…",
         "H = Σ λᵢ |eᵢ⟩⟨eᵢ|, a sum over its eigenvalues and orthonormal eigenvectors",
         ["H = Σ |eᵢ⟩⟨eⱼ| over all i and j", "H = U†U", "H = λI for a single eigenvalue λ"],
         "Every Hermitian operator is a weighted sum of projectors onto its eigenvectors, weighted by the eigenvalues."),
    ]),
    "maths-outer-tensor-products": ("quantum-maths", [
        ("Outer product", "easy",
         "What is the outer product |0⟩⟨0| written as a matrix?",
         "[[1, 0], [0, 0]]",
         ["[[0, 0], [0, 1]]", "[[1, 0], [0, 1]]", "[[0, 1], [1, 0]]"],
         "|0⟩⟨0| is the projector onto |0⟩: a 1 in the top-left corner and zeros elsewhere."),
        ("Completeness relation", "medium",
         "For an orthonormal basis {|i⟩}, the completeness relation states that…",
         "Σᵢ |i⟩⟨i| = I",
         ["Σᵢ ⟨i|i⟩ = 0", "Σᵢ |i⟩ = I", "The product of all |i⟩⟨i| equals I"],
         "Summing the projectors onto every basis vector gives the identity — the basis 'resolves' every vector."),
        ("Tensor product", "medium",
         "What is |0⟩ ⊗ |1⟩ in the two-qubit computational basis?",
         "|01⟩, the vector (0, 1, 0, 0)",
         ["|10⟩, the vector (0, 0, 1, 0)", "The vector (1, 1)", "The vector (0, 1)"],
         "In the ordering |00⟩, |01⟩, |10⟩, |11⟩, the state |0⟩⊗|1⟩ = |01⟩ has its single 1 in the second position."),
    ]),
    "maths-complex-analysis": ("quantum-maths", [
        ("Euler's formula", "easy",
         "Euler's formula states that e^(iθ) equals…",
         "cos θ + i sin θ",
         ["sin θ + i cos θ", "cos θ − sin θ", "1 + iθ"],
         "Euler's formula links the complex exponential to rotation in the complex plane: e^(iθ) = cos θ + i sin θ."),
        ("Global phase", "medium",
         "Why does multiplying a state by a global phase e^(iφ) not change any measurement result?",
         "Every probability depends on |amplitude|², and |e^(iφ)| = 1",
         ["Because φ is always zero", "Because measurement discards imaginary parts", "Because global phase only matters for single qubits"],
         "A global phase multiplies every amplitude by a number of modulus 1, so every |amplitude|² — and every probability — is unchanged."),
        ("Relative phase", "medium",
         "Which pair of states differ only by a relative phase?",
         "(|0⟩ + |1⟩)/√2 and (|0⟩ − |1⟩)/√2",
         ["|0⟩ and |1⟩", "|0⟩ and −|0⟩", "|0⟩ and (|0⟩ + |1⟩)/√2"],
         "|+⟩ and |−⟩ differ only by the phase on |1⟩. Unlike the global phase between |0⟩ and −|0⟩, this relative phase is measurable in the X basis."),
    ]),
    # ---------------------------------------------------------------- physics
    "physics-wave-particle-duality": ("quantum-physics", [
        ("De Broglie wavelength", "easy",
         "The de Broglie wavelength of a particle with momentum p is…",
         "λ = h/p",
         ["λ = p/h", "λ = hp", "λ = pc/h"],
         "De Broglie proposed that every particle has a wavelength inversely proportional to its momentum, λ = h/p."),
        ("Photoelectric effect", "medium",
         "In the photoelectric effect, raising the light's intensity at a fixed frequency (above threshold) increases…",
         "The number of emitted electrons, not their maximum kinetic energy",
         ["The maximum kinetic energy of each electron", "The metal's threshold frequency", "Nothing at all"],
         "Intensity sets how many photons arrive; each photon's energy hν — and so each electron's maximum energy — depends only on frequency."),
        ("Planck's quanta", "medium",
         "To explain black-body radiation, Planck proposed that energy is exchanged in quanta of size…",
         "E = hν",
         ["E = mc²", "E = kT", "E = ½mv²"],
         "Planck's hypothesis that energy comes in packets of hν resolved the ultraviolet catastrophe and started quantum theory."),
    ]),
    "physics-schrodinger-equation": ("quantum-physics", [
        ("Time-dependent equation", "easy",
         "Which is the time-dependent Schrödinger equation?",
         "iℏ ∂Ψ/∂t = ĤΨ",
         ["Ĥ = iℏΨ", "∂²Ψ/∂t² = ĤΨ", "ℏ ∂Ψ/∂x = EΨ"],
         "The Hamiltonian generates time evolution: iℏ ∂Ψ/∂t = ĤΨ."),
        ("Born rule", "medium",
         "According to the Born rule, |Ψ(x,t)|² represents…",
         "The probability density of finding the particle at x at time t",
         ["The particle's energy", "The particle's momentum", "The particle's exact position"],
         "The wavefunction is a probability amplitude; its squared modulus is a probability density."),
        ("Stationary states", "medium",
         "The time-independent Schrödinger equation ĤΨ = EΨ is…",
         "An eigenvalue equation whose eigenvalues are the allowed energies",
         ["A classical wave equation with no quantisation", "Valid only for free particles", "The rule for measurement collapse"],
         "Solving ĤΨ = EΨ finds the energy eigenstates; boundary conditions make only certain energies E allowed."),
    ]),
    "physics-uncertainty-principle": ("quantum-physics", [
        ("Heisenberg relation", "easy",
         "Heisenberg's uncertainty relation for position and momentum is…",
         "Δx Δp ≥ ℏ/2",
         ["Δx Δp ≤ ℏ/2", "Δx + Δp ≥ ℏ", "Δx Δp = 0"],
         "No state can have both arbitrarily sharp position and arbitrarily sharp momentum: their spreads multiply to at least ℏ/2."),
        ("Canonical commutator", "medium",
         "The canonical commutator [x̂, p̂] equals…",
         "iℏ",
         ["0", "ℏ", "−1"],
         "Position and momentum fail to commute by exactly iℏ, and this is the source of their uncertainty relation."),
        ("Origin of uncertainty", "medium",
         "The uncertainty principle arises because…",
         "Position and momentum operators do not commute",
         ["Measuring devices are imprecise", "Particles move too fast to track", "Energy is always conserved"],
         "The limit is built into the theory, not the instruments: non-commuting observables cannot share a complete set of eigenstates."),
    ]),
    "physics-stern-gerlach": ("quantum-physics", [
        ("Quantised spin", "easy",
         "When silver atoms passed through the inhomogeneous magnetic field of the 1922 Stern–Gerlach experiment, what was seen?",
         "The beam split into two separate spots, showing quantised angular momentum",
         ["A continuous smear of deflections", "No deflection at all", "Three equally spaced spots"],
         "Classically the deflections should form a continuous smear. Two discrete spots revealed spin's two quantised values."),
        ("Repeated measurement", "medium",
         "Atoms from the +z output of a z-oriented Stern–Gerlach device enter a second z-oriented device. What happens?",
         "They all come out in the +z beam",
         ["Half go +z and half −z", "They all go −z", "They are absorbed by the magnet"],
         "Repeating the same measurement gives the same result: the state is already the +z eigenstate."),
        ("Incompatible measurements", "hard",
         "+z atoms go through an x-oriented device, and its +x output then through a z-oriented device. What is observed?",
         "About half come out +z and half −z: measuring x erased the earlier z information",
         ["All come out +z", "All come out −z", "No atoms emerge"],
         "The +x state is an equal superposition of +z and −z, so the final z measurement is 50/50 — spin along x and z are incompatible observables."),
    ]),
    "physics-electron-spin": ("quantum-physics", [
        ("Pauli X", "easy",
         "Which matrix is the Pauli X matrix?",
         "[[0, 1], [1, 0]]",
         ["[[1, 0], [0, −1]]", "[[0, −i], [i, 0]]", "[[1, 0], [0, 1]]"],
         "σx swaps |0⟩ and |1⟩. [[1,0],[0,−1]] is σz and [[0,−i],[i,0]] is σy."),
        ("Pauli eigenvalues", "medium",
         "What are the eigenvalues of each Pauli matrix?",
         "+1 and −1",
         ["0 and 1", "+i and −i", "+2 and −2"],
         "Each Pauli matrix is Hermitian and squares to the identity, so its eigenvalues must be ±1."),
        ("Spin commutation", "medium",
         "The commutator [σx, σy] equals…",
         "2iσz",
         ["0", "σz", "−2σz"],
         "The Pauli matrices obey [σx, σy] = 2iσz (and cyclic permutations), mirroring the algebra of angular momentum."),
    ]),
    "physics-quantum-tunnelling": ("quantum-physics", [
        ("Tunnelling", "easy",
         "Quantum tunnelling is when a particle…",
         "Has a non-zero probability of passing through a barrier higher than its energy",
         ["Always reflects off any barrier", "Borrows energy to jump over the barrier classically", "Travels faster than light"],
         "Inside a classically forbidden barrier the wavefunction decays rather than vanishing, so some probability leaks through."),
        ("Particle in a box", "medium",
         "For a particle in a 1D infinite square well, the allowed energies scale as…",
         "n², for n = 1, 2, 3, …",
         ["n", "1/n", "√n"],
         "The allowed energies are Eₙ = n²π²ℏ²/(2mL²), so they grow with the square of the quantum number."),
        ("Barrier width", "medium",
         "How does the tunnelling probability through a rectangular barrier change as the barrier gets wider?",
         "It decreases roughly exponentially",
         ["It increases linearly", "It stays the same", "It drops to exactly zero at any finite width"],
         "The wavefunction decays exponentially inside the barrier, so each extra bit of width cuts transmission by a constant factor."),
    ]),
    # ------------------------------------------------- quantum machine learning
    "qml-01-introduction": ("quantum-machine-learning", [
        ("Why QML", "easy",
         "Why is machine learning a natural near-term target for quantum computers?",
         "Learning tolerates approximate, noisy outputs and can use short hybrid quantum-classical circuits",
         ["It requires fully error-corrected quantum computers", "Classical machine learning has been proven impossible", "Quantum computers can load unlimited classical data instantly"],
         "Learning tasks are naturally approximate, so they suit today's noisy hardware running short circuits alongside a classical computer."),
        ("Hybrid computing", "medium",
         "What does 'hybrid quantum-classical' mean in this course?",
         "A classical computer optimises parameters while a quantum device evaluates a circuit or draws samples",
         ["Quantum and classical bits are stored in the same memory cell", "The same program runs on both machines and the results are compared", "A classical simulation of a quantum computer only"],
         "In hybrid algorithms each machine does what it is good at: the quantum device prepares and measures states, the classical one optimises."),
        ("NISQ era", "easy",
         "What does NISQ stand for?",
         "Noisy Intermediate-Scale Quantum",
         ["Non-Interacting Superposed Qubits", "Networked Integrated Superconducting Quantum", "Noise-Immune Scalable Quantum"],
         "NISQ describes today's devices: tens to hundreds of noisy qubits without full error correction."),
    ]),
    "qml-02-classical-probability-theory": ("quantum-machine-learning", [
        ("Probability vectors", "easy",
         "A probability vector must have…",
         "Non-negative entries that sum to 1",
         ["Entries whose squares sum to 1", "Complex entries of modulus 1", "Entries that sum to 0"],
         "Probabilities are non-negative and must total 1 — the 1-norm is preserved, not the 2-norm used for quantum states."),
        ("Stochastic matrices", "medium",
         "A column-stochastic matrix maps probability vectors to probability vectors because…",
         "Its entries are non-negative and each column sums to 1",
         ["It is unitary", "It is Hermitian", "Its determinant is 1"],
         "Non-negative entries keep probabilities non-negative, and columns summing to 1 keep the total probability at 1."),
        ("Preserved norm", "medium",
         "Probability vectors preserve the 1-norm. Which norm does a quantum state preserve?",
         "The 2-norm (Euclidean length)",
         ["The 1-norm", "The infinity-norm", "No norm at all"],
         "Quantum amplitudes can be negative or complex; it is the sum of their squared moduli — the 2-norm — that stays equal to 1."),
    ]),
    "qml-03-quantum-states": ("quantum-machine-learning", [
        ("Born rule", "easy",
         "By the Born rule, measuring α|0⟩ + β|1⟩ gives outcome 0 with probability…",
         "|α|²",
         ["α", "|α|", "α² (without the modulus)"],
         "Probabilities are the squared moduli of the amplitudes, which is why complex amplitudes still give real, non-negative probabilities."),
        ("Global phase", "medium",
         "Why is −|ψ⟩ physically the same state as |ψ⟩?",
         "They differ only by a global phase of −1, which no measurement can detect",
         ["They are not the same: they give different Z-basis statistics", "Because −1 is not a valid amplitude", "Because the sign is lost when the state is stored"],
         "A global phase multiplies every amplitude equally, so every measurement probability in every basis is unchanged."),
        ("Relative phase", "medium",
         "|+⟩ and |−⟩ give identical Z-basis statistics. How can they be told apart?",
         "Measure in the X basis (or apply H before a Z measurement)",
         ["Measure in the Z basis more times", "Apply a global phase", "Measure the norm of the state"],
         "Their difference is a relative phase, which becomes visible in the X basis: H maps |+⟩ to |0⟩ and |−⟩ to |1⟩."),
    ]),
    "qml-04-multiple-qubits": ("quantum-machine-learning", [
        ("Tensor product", "easy",
         "How is the joint state of two independent qubits formed?",
         "With the tensor product of the two single-qubit states",
         ["By adding the state vectors", "By multiplying the amplitudes element-wise", "By taking their inner product"],
         "Composite systems combine with the tensor product, so the dimension multiplies: 2 × 2 = 4 for two qubits."),
        ("Entangled states", "medium",
         "Which of these states is entangled?",
         "(|00⟩ + |11⟩)/√2",
         ["|0⟩ ⊗ |1⟩", "(|00⟩ + |01⟩)/√2", "|+⟩ ⊗ |+⟩"],
         "(|00⟩ + |01⟩)/√2 factorises as |0⟩⊗|+⟩, but the Bell state (|00⟩ + |11⟩)/√2 cannot be written as any product."),
        ("Definition of entanglement", "medium",
         "What does it mean for a two-qubit state to be entangled?",
         "It cannot be written as a tensor product of two single-qubit states",
         ["Both qubits are in |1⟩", "The qubits are physically touching", "All its amplitudes are equal"],
         "Entanglement is defined by non-separability: the joint state has correlations no product state can reproduce."),
    ]),
    "qml-05-measurements": ("quantum-machine-learning", [
        ("Post-measurement state", "easy",
         "A qubit is measured in the computational basis and the result is 1. What is its state afterwards?",
         "|1⟩",
         ["Unchanged", "(|0⟩ + |1⟩)/√2", "|0⟩"],
         "A projective measurement collapses the state onto the eigenvector for the observed outcome."),
        ("Expectation value", "medium",
         "The expectation value of an observable A in the state |ψ⟩ is…",
         "⟨ψ|A|ψ⟩",
         ["⟨ψ|ψ⟩", "A|ψ⟩", "Tr(A)"],
         "⟨ψ|A|ψ⟩ is the average measured value of A over many identically prepared copies of |ψ⟩."),
        ("Computing ⟨Z⟩", "medium",
         "What is ⟨Z⟩ for the state |+⟩ = (|0⟩ + |1⟩)/√2?",
         "0",
         ["1", "−1", "1/√2"],
         "|+⟩ gives +1 and −1 each with probability ½, so the average of Z is ½(+1) + ½(−1) = 0."),
    ]),
    "qml-06-mixed-states": ("quantum-machine-learning", [
        ("Density matrix conditions", "easy",
         "Which conditions must a density matrix ρ satisfy?",
         "Hermitian, positive semi-definite, and Tr(ρ) = 1",
         ["Unitary, with Tr(ρ) = 0", "Diagonal, with entries summing to 2", "ρ² = 0"],
         "These conditions guarantee that ρ assigns real, non-negative probabilities that add up to 1."),
        ("Purity", "medium",
         "What is the purity Tr(ρ²) of a pure state?",
         "1",
         ["0", "½", "It depends on the basis"],
         "For a pure state ρ = |ψ⟩⟨ψ|, so ρ² = ρ and Tr(ρ²) = 1. Mixed states have purity below 1."),
        ("Maximally mixed state", "medium",
         "What is the density matrix of the maximally mixed single-qubit state?",
         "I/2",
         ["|0⟩⟨0|", "|+⟩⟨+|", "I"],
         "I/2 gives every outcome probability ½ in every basis — total ignorance. Note I alone has trace 2, not 1."),
    ]),
    "qml-07-evolution-in-closed-quantum-systems": ("quantum-machine-learning", [
        ("Unitary evolution", "easy",
         "The evolution of a closed quantum system is described by…",
         "A unitary operator",
         ["A stochastic matrix", "A projection", "Any invertible matrix"],
         "Isolated systems evolve unitarily, which keeps states normalised and makes the evolution reversible."),
        ("Time evolution operator", "medium",
         "For a time-independent Hamiltonian H, the evolution operator is…",
         "U(t) = e^(−iHt/ℏ)",
         ["U(t) = Ht", "U(t) = e^(Ht)", "U(t) = I − Ht"],
         "Solving the Schrödinger equation for constant H gives U(t) = e^(−iHt/ℏ), which is unitary because H is Hermitian."),
        ("Why unitary", "medium",
         "Why must closed-system evolution be unitary?",
         "It preserves the norm, so total probability stays equal to 1",
         ["It makes the state Hermitian", "It forces all amplitudes to be real", "It makes evolution irreversible"],
         "Norm preservation is exactly what unitarity guarantees, keeping the probabilities of all outcomes summing to 1."),
    ]),
    "qml-08-open-quantum-systems": ("quantum-machine-learning", [
        ("Decoherence", "easy",
         "What is decoherence?",
         "The loss of quantum coherence as a system becomes entangled with its environment",
         ["A qubit gaining energy from a gate", "A software bug in the simulator", "Measuring in the X basis"],
         "Coupling to the environment leaks phase information out of the system, turning superpositions into classical mixtures."),
        ("Gibbs state", "medium",
         "A thermal (Gibbs) state has the form ρ ∝ …",
         "e^(−H/kT), normalised by the partition function",
         ["e^(H/kT)", "H/kT", "The ground-state projector, at every temperature"],
         "Thermal states weight each energy level by its Boltzmann factor e^(−E/kT), divided by the partition function Z."),
        ("Low-temperature limit", "medium",
         "As temperature approaches zero, a thermal state approaches…",
         "The ground state",
         ["The maximally mixed state", "The highest-energy state", "An equal superposition of all states"],
         "As T → 0 the Boltzmann factors of every excited state vanish relative to the ground state's."),
    ]),
    "qml-09-classical-ising-model": ("quantum-machine-learning", [
        ("Ising spins", "easy",
         "In the Ising model, each spin takes the values…",
         "+1 or −1",
         ["Any real number", "Anything from 0 to 1", "Any complex number of modulus 1"],
         "Ising spins are binary variables, which is what makes the model a natural home for combinatorial problems."),
        ("Ising energy", "medium",
         "The Ising energy function is typically written as…",
         "E = −Σ Jᵢⱼ σᵢσⱼ − Σ hᵢ σᵢ",
         ["E = Σ σᵢ²", "E = the product of all Jᵢⱼ σᵢσⱼ", "E = Σ hᵢ only, with no couplings"],
         "Couplings Jᵢⱼ reward or penalise aligned neighbours, and local fields hᵢ bias individual spins."),
        ("Ising and optimisation", "medium",
         "Why is the Ising model central to quantum optimisation?",
         "Many combinatorial problems can be mapped onto finding its lowest-energy spin configuration",
         ["It describes a single qubit's rotation", "It has no connection to optimisation", "It can only model ferromagnets"],
         "Encode a problem's cost in the couplings and fields, and its best solution becomes the Ising ground state."),
    ]),
    "qml-10-transverse-field-ising-model": ("quantum-machine-learning", [
        ("Non-commuting terms", "easy",
         "What makes the transverse-field Ising Hamiltonian genuinely quantum?",
         "It contains terms that do not commute — σᶻσᶻ couplings and a σˣ field",
         ["It only uses complex couplings", "It has more than two spins", "It is written in Dirac notation"],
         "The σˣ field does not commute with the σᶻσᶻ couplings, so the ground state is not a classical spin configuration."),
        ("Strong-field limit", "medium",
         "When the transverse field dominates, the ground state is close to…",
         "Every spin pointing along x, i.e. |+⟩ on every site",
         ["Every spin up along z", "An alternating z pattern", "The maximally mixed state"],
         "A strong −hΣσˣ term is minimised by aligning each spin with +x, the state |+⟩."),
        ("Role in annealing", "medium",
         "In quantum annealing, the transverse field is used to…",
         "Create quantum fluctuations that let the system explore configurations",
         ["Measure the final state", "Cool the processor", "Fix the couplings Jᵢⱼ"],
         "The field starts strong so the system is in an easy superposition, then is turned down so the problem Hamiltonian takes over."),
    ]),
    "qml-11-quantum-many-body-physics": ("quantum-machine-learning", [
        ("Exponential Hilbert space", "easy",
         "Why are many-body quantum systems hard to simulate classically?",
         "The Hilbert space dimension grows exponentially with the number of particles",
         ["Their Hamiltonians are always non-Hermitian", "They need relativistic equations", "They have no ground state"],
         "Each added particle multiplies the dimension, so storing a general state quickly outgrows any classical memory."),
        ("State size", "medium",
         "How many complex amplitudes describe a general state of 50 qubits?",
         "2⁵⁰, about 10¹⁵",
         ["50", "100", "50²"],
         "Fifty qubits need 2⁵⁰ ≈ 1.1 × 10¹⁵ amplitudes — petabytes of memory on a classical machine."),
        ("Exploiting structure", "medium",
         "Why do physicists look for structure, such as limited entanglement, in many-body states?",
         "Structured states can be represented far more compactly than a general state",
         ["Structured states are always classical", "It makes the Hilbert space smaller", "Only structured states obey the Schrödinger equation"],
         "Physically relevant states often occupy a tiny corner of Hilbert space, which efficient representations can exploit."),
    ]),
    "qml-12-many-body-behavior-of-spins": ("quantum-machine-learning", [
        ("Order parameter", "easy",
         "What is an order parameter?",
         "A quantity that distinguishes phases, such as magnetisation in a ferromagnet",
         ["The order in which gates are applied", "The number of spins", "The system's temperature"],
         "An order parameter is zero in one phase and non-zero in another, marking which phase the system is in."),
        ("Phase transition", "medium",
         "A phase transition happens when…",
         "The system's macroscopic behaviour changes qualitatively as a parameter crosses a critical value",
         ["A single spin flips", "The Hamiltonian becomes non-Hermitian", "A measurement collapses the state"],
         "Phase transitions are collective changes — for example, a magnet losing its magnetisation above a critical temperature."),
        ("Ferromagnetic order", "easy",
         "In a ferromagnetic phase, neighbouring spins tend to…",
         "Align in the same direction",
         ["Point in opposite directions", "Point randomly with no correlation", "Vanish"],
         "Ferromagnetic couplings lower the energy of aligned neighbours, producing a net magnetisation."),
    ]),
    "qml-13-strategies-to-solve-the-many-body-problem": ("quantum-machine-learning", [
        ("Tensor networks", "easy",
         "Which method represents a many-body state as a network of small connected tensors?",
         "Tensor networks, such as matrix product states",
         ["Monte Carlo sampling", "Exact diagonalisation", "Fourier analysis"],
         "Tensor networks compress states with limited entanglement into chains or grids of small tensors."),
        ("Quantum Monte Carlo", "medium",
         "Quantum Monte Carlo estimates properties by…",
         "Randomly sampling configurations",
         ["Diagonalising the full Hamiltonian exactly", "Building a quantum circuit", "Solving the problem analytically"],
         "Monte Carlo methods replace an exponential sum with statistical sampling, but can suffer from the sign problem."),
        ("Neural-network states", "medium",
         "What is a neural-network quantum state?",
         "A neural network whose outputs give the amplitudes of a wavefunction",
         ["A neural network running on a quantum computer", "A classical dataset of measurement results", "A model of the brain as a quantum system"],
         "The network takes a spin configuration as input and returns its amplitude, acting as a compact variational ansatz."),
    ]),
    "qml-14-gate-model-quantum-computing": ("quantum-machine-learning", [
        ("Universal gate sets", "easy",
         "A universal gate set can…",
         "Approximate any unitary to arbitrary accuracy",
         ["Only create entanglement", "Only perform classical logic", "Run without decoherence"],
         "Universality means any quantum computation can be built, to any desired precision, from the set's gates."),
        ("Circuit depth", "medium",
         "Why does circuit depth matter on current hardware?",
         "Deeper circuits take longer, so decoherence and gate errors accumulate",
         ["Depth has no effect on results", "Deeper circuits use fewer qubits", "Depth only affects classical post-processing"],
         "Every layer adds time and error, so the coherence time limits how deep a useful circuit can be."),
        ("A universal set", "medium",
         "Which of these gate sets is universal for quantum computation?",
         "Arbitrary single-qubit rotations plus CNOT",
         ["Only X and Z gates", "Only Hadamard gates", "Only measurements"],
         "Single-qubit rotations plus one entangling gate such as CNOT can generate any unitary."),
    ]),
    "qml-15-adiabatic-quantum-computing": ("quantum-machine-learning", [
        ("Adiabatic theorem", "easy",
         "The adiabatic theorem says a system stays in its instantaneous ground state if…",
         "The Hamiltonian is changed slowly enough relative to the energy gap",
         ["The Hamiltonian is changed as fast as possible", "The temperature is high", "The system is measured frequently"],
         "Slow evolution keeps the system from being excited across the gap to higher-energy states."),
        ("Spectral gap", "medium",
         "What sets the required runtime of an adiabatic algorithm?",
         "The minimum spectral gap between the ground and first excited states",
         ["The number of measurements", "The initial energy", "The number of classical bits"],
         "The smaller the minimum gap, the slower the evolution must be — runtime scales roughly with 1/gap²."),
        ("Starting state", "medium",
         "An adiabatic computation normally starts in…",
         "The easy-to-prepare ground state of a simple initial Hamiltonian",
         ["The answer state", "A random excited state", "The maximally mixed state"],
         "You begin in a known ground state, then slowly morph the Hamiltonian into the problem Hamiltonian whose ground state is the answer."),
    ]),
    "qml-16-quantum-annealing": ("quantum-machine-learning", [
        ("Annealing vs adiabatic", "easy",
         "How does quantum annealing differ from ideal adiabatic quantum computing?",
         "It runs at finite temperature and speed, so it is a practical heuristic approximation",
         ["It uses gates instead of Hamiltonians", "It needs error-corrected qubits", "It only solves linear systems"],
         "Real annealers cannot run infinitely slowly at zero temperature, so they give good but not guaranteed solutions."),
        ("Native problems", "medium",
         "What kind of problem do D-Wave-style annealers natively solve?",
         "Finding low-energy states of Ising or QUBO problems",
         ["Factoring integers with Shor's algorithm", "Running arbitrary gate circuits", "Simulating chemistry exactly"],
         "Annealers physically implement an Ising Hamiltonian, so problems must be expressed as Ising or QUBO form."),
        ("QUBO", "easy",
         "What does QUBO stand for?",
         "Quadratic Unconstrained Binary Optimisation",
         ["Quantum Unitary Binary Operation", "Qubit Universal Basis Optimisation", "Quadratic Unitary Boolean Output"],
         "A QUBO minimises a quadratic function of binary variables, and maps directly onto an Ising model."),
    ]),
    "qml-17-implementations": ("quantum-machine-learning", [
        ("Superconducting qubits", "easy",
         "Superconducting qubits generally have to be cooled to…",
         "Millikelvin temperatures, in a dilution refrigerator",
         ["Room temperature", "About 77 K with liquid nitrogen", "About 4 K and no lower"],
         "Thermal noise must be far below the qubit's energy splitting, which means around 10–20 mK."),
        ("Trapped ions", "medium",
         "A notable strength of trapped-ion qubits is…",
         "Long coherence times and high-fidelity gates, with all-to-all connectivity",
         ["The fastest gate speeds of any platform", "No need for control lasers", "Running at room temperature without a vacuum"],
         "Ions are near-identical and well isolated, giving long coherence and flexible connectivity, though their gates are slower."),
        ("Comparing platforms", "medium",
         "When comparing hardware platforms, why is qubit count alone not enough?",
         "Connectivity, gate fidelity and coherence time also decide what can actually run",
         ["More qubits always means better results", "Qubit count is the only published metric", "All qubits are identical across platforms"],
         "A few high-quality, well-connected qubits can beat many noisy ones on real algorithms."),
    ]),
    "qml-18-quantum-approximate-optimization-algorithm": ("quantum-machine-learning", [
        ("QAOA layers", "easy",
         "QAOA alternates between applying…",
         "A cost (problem) Hamiltonian and a mixer Hamiltonian",
         ["Only measurements and resets", "Only Hadamard gates", "Classical and quantum error correction"],
         "Each of the p layers applies e^(−iγH_C) then e^(−iβH_M), discretising an adiabatic path."),
        ("Classical optimiser", "medium",
         "What does the classical optimiser do in QAOA?",
         "Tunes the angles γ and β to minimise the expected cost",
         ["Solves the problem exactly first", "Designs the hardware layout", "Corrects measurement errors"],
         "The quantum device evaluates the cost for given angles, and the classical optimiser searches for better ones."),
        ("Large p limit", "hard",
         "As the number of QAOA layers p grows without limit, QAOA can…",
         "Approach the adiabatic path and reach the optimal solution",
         ["Only get worse", "Solve NP-hard problems in constant time", "Stop needing measurements"],
         "With enough layers, QAOA can reproduce slow adiabatic evolution, so in the limit it reaches the ground state."),
    ]),
    "qml-19-sampling-a-thermal-state": ("quantum-machine-learning", [
        ("Why thermal sampling", "easy",
         "Why is sampling from a Boltzmann (thermal) distribution useful in machine learning?",
         "Training energy-based models such as Boltzmann machines needs those samples",
         ["It sorts the data", "It encrypts the training data", "It removes the need for a model"],
         "The gradients of energy-based models depend on averages over the model's own Boltzmann distribution."),
        ("Boltzmann weights", "easy",
         "In a Boltzmann distribution, low-energy configurations are…",
         "Exponentially more likely than high-energy ones",
         ["Less likely", "Equally likely", "Impossible"],
         "Each configuration's probability is proportional to e^(−E/kT), so lower energy means exponentially higher probability."),
        ("Annealers as samplers", "medium",
         "Why might a quantum annealer be used as a sampler?",
         "Its finite-temperature output approximates samples from a thermal distribution",
         ["It always returns the exact ground state", "It measures the partition function directly", "Its output contains no randomness"],
         "Annealers do not reliably reach the ground state; that imperfection makes their outputs useful as approximate thermal samples."),
    ]),
    "qml-20-variational-circuits-and-quantum-simulation-1": ("quantum-machine-learning", [
        ("Variational principle", "easy",
         "For any normalised trial state |ψ(θ)⟩, the variational principle states that…",
         "⟨ψ(θ)|H|ψ(θ)⟩ ≥ E₀, the true ground-state energy",
         ["⟨ψ(θ)|H|ψ(θ)⟩ ≤ E₀", "⟨ψ(θ)|H|ψ(θ)⟩ = E₀ always", "The energy does not depend on θ"],
         "No trial state can have energy below the ground state, so minimising the energy over θ approaches E₀ from above."),
        ("Quantum role", "medium",
         "In a variational quantum algorithm, the quantum computer's job is to…",
         "Prepare the parameterised trial state and measure its energy",
         ["Choose the next parameters", "Store the whole Hamiltonian matrix", "Run classical gradient descent"],
         "The quantum device handles the hard part — preparing and measuring the state — while a classical optimiser updates θ."),
        ("VQE", "easy",
         "What does VQE stand for?",
         "Variational Quantum Eigensolver",
         ["Very Quick Entangler", "Virtual Quantum Engine", "Variable Qubit Encoding"],
         "VQE finds ground-state energies by variationally minimising ⟨H⟩ with a hybrid quantum-classical loop."),
    ]),
    "qml-21-variational-circuits-and-quantum-simulation-2": ("quantum-machine-learning", [
        ("Fermion-to-qubit mapping", "easy",
         "To run VQE on a molecule, its fermionic Hamiltonian is first…",
         "Mapped to qubit operators, for example with the Jordan–Wigner transformation",
         ["Measured directly on the electrons", "Converted into a classical neural network", "Ignored in favour of the nuclear Hamiltonian"],
         "Electrons are fermions; mappings like Jordan–Wigner or Bravyi–Kitaev rewrite their operators as Pauli strings on qubits."),
        ("Measurement grouping", "medium",
         "Why are Hamiltonian terms grouped into commuting sets?",
         "Commuting terms can be measured together, cutting the number of circuit runs",
         ["It makes the Hamiltonian Hermitian", "It removes the need for a classical optimiser", "It beats the variational bound"],
         "Terms that commute share a measurement basis, so one set of shots estimates all of them at once."),
        ("Pauli decomposition", "medium",
         "The Hamiltonian in VQE is usually written as…",
         "A weighted sum of Pauli strings",
         ["A single unitary gate", "A probability vector", "The density matrix of the answer"],
         "Writing H = Σ cᵢ Pᵢ lets each Pauli string's expectation value be measured on hardware and summed."),
    ]),
    "qml-22-variational-circuits-and-quantum-simulation-3": ("quantum-machine-learning", [
        ("Hardware-efficient ansatz", "easy",
         "What is a hardware-efficient ansatz?",
         "A circuit built from the gates and connectivity the device runs natively",
         ["A circuit derived purely from chemistry theory", "An ansatz with no parameters", "A classical approximation of the circuit"],
         "It trades physical motivation for shallow depth on real hardware."),
        ("Chemistry-inspired ansatz", "medium",
         "Chemistry-inspired ansätze such as UCCSD come from…",
         "Coupled-cluster theory in quantum chemistry",
         ["Image-recognition networks", "Random circuit sampling", "Error-correcting codes"],
         "Unitary coupled cluster builds the trial state from excitations of a reference state, following classical coupled-cluster theory."),
        ("Barren plateaus", "hard",
         "What is a barren plateau?",
         "A training landscape whose gradients vanish exponentially as the system grows",
         ["An empty region of the Bloch sphere", "A hardware failure mode", "The optimum of a cost function"],
         "In a barren plateau, gradients are so small that estimating them needs exponentially many shots, stalling training."),
    ]),
    "qml-23-variational-circuits-and-quantum-simulation-4": ("quantum-machine-learning", [
        ("Error mitigation", "easy",
         "What is the goal of error mitigation, as opposed to error correction?",
         "To reduce noise's effect on estimated results without full fault tolerance",
         ["To remove every error using logical qubits", "To increase circuit depth", "To avoid measuring at all"],
         "Mitigation post-processes noisy results to improve estimates; it needs no extra encoded qubits."),
        ("Zero-noise extrapolation", "medium",
         "In zero-noise extrapolation, you…",
         "Run at several amplified noise levels and extrapolate the result back to zero noise",
         ["Switch the noise off in hardware", "Only use noiseless simulators", "Measure each qubit zero times"],
         "Deliberately increasing noise shows how results depend on it, so you can extrapolate to the noise-free value."),
        ("Classical benchmarks", "medium",
         "Why must variational quantum simulation be compared with the best classical methods?",
         "A quantum result only matters if classical methods cannot match it at similar cost",
         ["Classical methods are always wrong", "To calibrate qubit frequencies", "The Schrödinger equation requires it"],
         "Demonstrating value means beating strong classical baselines, not just producing an answer."),
    ]),
    "qml-24-encoding-classical-information": ("quantum-machine-learning", [
        ("Basis encoding", "easy",
         "Basis encoding represents the bit string 101 as…",
         "The computational basis state |101⟩",
         ["The amplitude vector (1, 0, 1)", "A rotation by 101 radians", "Three separate measurements"],
         "Each classical bit becomes the corresponding qubit's basis state."),
        ("Amplitude encoding", "medium",
         "Amplitude encoding stores a normalised N-dimensional vector in…",
         "The amplitudes of about log₂N qubits",
         ["N qubits", "N² qubits", "A single qubit, whatever N is"],
         "n qubits have 2ⁿ amplitudes, so N values fit in log₂N qubits — an exponential compression."),
        ("State preparation cost", "medium",
         "What is the main practical catch of amplitude encoding?",
         "Preparing an arbitrary state can take so many gates that it cancels the speed-up",
         ["It needs no gates at all", "It only works for binary data", "It cannot represent real numbers"],
         "Loading arbitrary data generally costs O(N) operations, which can erase an algorithm's claimed advantage."),
    ]),
    "qml-25-ensemble-learning": ("quantum-machine-learning", [
        ("Ensembles", "easy",
         "What is an ensemble method?",
         "Combining several weak learners into a stronger model",
         ["Training one very large model", "Averaging a single model over time", "A method that uses no data"],
         "Ensembles pool many modest models so that their individual errors partly cancel."),
        ("Boosting", "medium",
         "Boosting builds its ensemble by…",
         "Training learners one after another, focusing on examples the earlier ones got wrong",
         ["Training every learner independently on identical data", "Dropping all weak learners", "Using only the first learner"],
         "Boosting reweights misclassified examples so each new learner concentrates on the remaining mistakes."),
        ("Selection as optimisation", "medium",
         "Why can choosing which weak learners to keep be framed as an optimisation problem?",
         "It means picking a binary subset that balances accuracy against model size",
         ["It requires computing gradients of decision trees", "The answer is always to keep every learner", "It needs quantum measurements"],
         "Each learner is in or out — a binary choice — and the objective trades training error against complexity."),
    ]),
    "qml-26-qboost": ("quantum-machine-learning", [
        ("QBoost formulation", "easy",
         "QBoost casts ensemble selection as…",
         "A QUBO problem solved on a quantum annealer",
         ["A linear system solved with HHL", "A Fourier transform", "A shortest-path problem"],
         "Choosing weak learners becomes a quadratic binary optimisation, which annealers solve natively."),
        ("Regularisation", "medium",
         "Why does QBoost include a regularisation term?",
         "It penalises using many weak learners, producing a sparse classifier",
         ["It forces every learner to be included", "It removes all errors", "It makes the problem continuous"],
         "The penalty on the number of selected learners avoids overfitting and keeps the final model small."),
        ("Binary variables", "medium",
         "In QBoost, each binary variable represents…",
         "Whether a particular weak learner is included in the ensemble",
         ["A training example's label", "A qubit's phase", "A pixel of the input image"],
         "One spin or bit per weak learner encodes the in-or-out decision."),
    ]),
    "qml-27-clustering-by-quantum-optimization": ("quantum-machine-learning", [
        ("Clustering as Ising", "easy",
         "Clustering can be written as an Ising problem by…",
         "Using spins for cluster assignments and pairwise distances as the couplings",
         ["Encoding each data point as a gate", "Taking the Fourier transform of the data", "Measuring each point's Z value"],
         "Each point's spin records its cluster, and distance-based couplings make the lowest-energy state a good clustering."),
        ("Two-cluster energy", "medium",
         "In a two-cluster Ising formulation, the energy is lowest when…",
         "Points that are far apart are assigned to different clusters",
         ["All points are in one cluster", "Points are assigned at random", "Nearby points are split apart"],
         "Couplings reward separating distant points (and keeping close ones together), so the ground state is a sensible split."),
        ("What it replaces", "medium",
         "Which kind of classical algorithm does this approach replace for finding assignments?",
         "Iterative heuristics such as k-means",
         ["Gradient boosting", "Shor's algorithm", "Backpropagation"],
         "Instead of iterating assignments as k-means does, the whole assignment is found by minimising one energy."),
    ]),
    "qml-28-kernel-methods": ("quantum-machine-learning", [
        ("Kernel trick", "easy",
         "The kernel trick lets you…",
         "Compute inner products in a high-dimensional feature space without building that space explicitly",
         ["Avoid computing any inner products", "Reduce every dataset to one dimension", "Train without labels"],
         "A kernel evaluates ⟨φ(x), φ(x′)⟩ directly, so the (possibly huge) feature vectors never need to be written out."),
        ("Kernel as inner product", "medium",
         "A kernel function k(x, x′) corresponds to…",
         "An inner product ⟨φ(x), φ(x′)⟩ between feature maps",
         ["The distance between two labels", "The derivative of the loss", "A random weight"],
         "Every valid kernel is an inner product in some feature space — the idea quantum kernels build on."),
        ("Support vector machines", "medium",
         "A support vector machine classifies by…",
         "Finding the separating hyperplane with the largest margin",
         ["Averaging all training labels", "Weighting every training point equally", "Building a decision tree"],
         "SVMs maximise the margin to the nearest points, the support vectors, which helps generalisation."),
    ]),
    "qml-29-an-interference-circuit": ("quantum-machine-learning", [
        ("Interference for similarity", "easy",
         "The interference circuit estimates how similar two data points are by…",
         "Encoding them and letting interference turn their inner product into a measurement probability",
         ["Measuring each point separately and comparing bits", "Running Shor's algorithm", "Adding their amplitudes classically"],
         "Interference makes the probability of an outcome depend on the overlap between the encoded states."),
        ("Swap test", "hard",
         "In the swap test, the probability of measuring the ancilla in |0⟩ is…",
         "(1 + |⟨φ|ψ⟩|²)/2",
         ["|⟨φ|ψ⟩|", "0 for identical states", "½ always"],
         "Identical states give probability 1 and orthogonal states give ½, so the statistics reveal the overlap."),
        ("Hadamard on the ancilla", "medium",
         "Which gate is central to creating the interference in these circuits?",
         "A Hadamard gate on an ancilla qubit",
         ["The identity gate", "Only a Z-basis measurement", "A classical AND gate"],
         "Hadamards put the ancilla into superposition and then recombine the two branches so they interfere."),
    ]),
    "qml-30-probabilistic-graphical-models": ("quantum-machine-learning", [
        ("Bayesian networks", "easy",
         "A Bayesian network is…",
         "A directed acyclic graph encoding conditional dependencies between variables",
         ["An undirected graph of qubits", "A neural network with no hidden layers", "A lookup table of every outcome"],
         "Edges point from causes to effects, and the joint distribution factorises into conditional probabilities."),
        ("Partition function", "medium",
         "The partition function Z of a graphical model…",
         "Normalises the distribution by summing over all configurations",
         ["Counts the number of nodes", "Always equals 1 before normalising", "Measures the model's accuracy"],
         "Dividing by Z turns the unnormalised weights into probabilities that sum to 1."),
        ("Hard inference", "medium",
         "Why is exact inference in general graphical models hard?",
         "Computing Z or marginals can require summing over exponentially many configurations",
         ["The graphs are always infinite", "Probabilities can be negative", "There is no training data"],
         "With n binary variables there are 2ⁿ configurations to sum over — the bottleneck quantum samplers aim at."),
    ]),
    "qml-31-optimization-and-sampling-in-pgms": ("quantum-machine-learning", [
        ("Contrastive divergence", "easy",
         "Contrastive divergence trains Boltzmann machines using…",
         "Short Gibbs-sampling runs to approximate the gradient",
         ["An exact computation of the partition function", "Backpropagation through a quantum circuit", "Genetic algorithms"],
         "A few Markov chain steps from the data give a cheap, biased estimate of the model's correlations."),
        ("Why quantum samplers", "medium",
         "Why are quantum samplers proposed for training graphical models?",
         "Drawing good samples from the model distribution is the training bottleneck",
         ["Graphical models can only run on quantum hardware", "Quantum samplers remove the need for data", "Classical sampling is impossible"],
         "Better samples mean better gradient estimates, which is where a quantum thermal sampler could help."),
        ("Log-likelihood gradient", "hard",
         "The log-likelihood gradient of a Boltzmann machine is the difference between…",
         "Correlations measured on the data and correlations under the model",
         ["Two random numbers", "The weights and the biases", "Training and test accuracy"],
         "Learning pushes the model's correlations toward the data's; the model term is the part that needs sampling."),
    ]),
    "qml-32-quantum-enhanced-kernel-methods-1": ("quantum-machine-learning", [
        ("Quantum feature map", "easy",
         "In quantum kernel methods, the feature map is…",
         "A quantum circuit that encodes x into a quantum state |φ(x)⟩",
         ["A classical polynomial expansion", "A measurement basis", "The label vector"],
         "The circuit embeds data into a Hilbert space that can be exponentially large."),
        ("Quantum kernel", "medium",
         "The quantum kernel between two inputs is usually defined as…",
         "|⟨φ(x)|φ(x′)⟩|², the overlap of the encoded states",
         ["x · x′", "The number of qubits", "The circuit depth"],
         "The overlap of the two feature states plays the role of the inner product in the kernel trick."),
        ("Using the kernel", "medium",
         "Once the kernel matrix is estimated, it is used by…",
         "A classical kernel method such as an SVM, which trains on it",
         ["The quantum computer, which trains the SVM itself", "Nobody — it is only for visualisation", "The data-encoding circuit"],
         "The quantum device only supplies kernel values; training happens classically."),
    ]),
    "qml-33-quantum-enhanced-kernel-methods-2": ("quantum-machine-learning", [
        ("Shot cost", "easy",
         "Why does estimating each kernel entry on hardware have a cost?",
         "Each overlap is estimated from repeated measurements (shots), with statistical error",
         ["Each entry needs a new quantum computer", "Entries are exact after a single shot", "Entries must be computed classically anyway"],
         "Probabilities are only estimated from finitely many shots, so precision costs repetitions."),
        ("Kernel matrix size", "medium",
         "For N training points, roughly how many kernel entries must be estimated?",
         "About N², one per pair of points",
         ["N", "log N", "2ᴺ"],
         "The kernel matrix has an entry for every pair, so the work grows quadratically with the dataset."),
        ("Link to variational models", "hard",
         "How are variational quantum classifiers related to kernel methods?",
         "A model that measures an encoded state is linear in the quantum feature space, just like a kernel method",
         ["They never use feature maps", "They cost exactly as much as classical SVMs", "They require no training"],
         "Both use the same feature map; kernel methods optimise over it implicitly, variational models explicitly."),
    ]),
    "qml-34-quantum-enhanced-kernel-methods-3": ("quantum-machine-learning", [
        ("Condition for advantage", "easy",
         "For a quantum kernel to offer an advantage, it must be…",
         "Hard to compute classically, yet still useful for the learning task",
         ["Easy to simulate classically", "Constant for all inputs", "Computable with a single qubit"],
         "Both conditions are needed: classical intractability alone is useless if the kernel does not fit the data."),
        ("Too much expressivity", "medium",
         "What happens if a quantum kernel is too expressive, so entries are near zero for distinct points?",
         "The model generalises poorly and needs exponentially many shots to resolve the entries",
         ["It always generalises perfectly", "Training becomes instant", "It becomes a classical linear kernel"],
         "A near-diagonal kernel memorises the training set and has entries too small to estimate reliably."),
        ("Classical simulability", "medium",
         "If a quantum kernel is classically simulable, it…",
         "Can be computed efficiently on a classical computer, removing any quantum advantage",
         ["Runs faster on quantum hardware", "Cannot be computed at all", "Only works for images"],
         "If a classical machine can compute the same kernel efficiently, the quantum device adds nothing."),
    ]),
    "qml-35-quantum-fourier-transform": ("quantum-machine-learning", [
        ("QFT gate count", "easy",
         "Roughly how many gates does the QFT on n qubits use?",
         "O(n²)",
         ["O(2ⁿ)", "O(n · 2ⁿ)", "O(1)"],
         "The QFT needs about n(n+1)/2 gates, exponentially fewer than the classical FFT's O(n·2ⁿ) operations on 2ⁿ values."),
        ("Classical analogue", "easy",
         "The QFT is the quantum analogue of…",
         "The discrete Fourier transform",
         ["The Laplace transform", "Gradient descent", "Matrix inversion"],
         "The QFT applies the DFT to a state's amplitudes."),
        ("Reading the output", "medium",
         "Why can't the QFT's speed-up simply be used to read out all the Fourier coefficients?",
         "They are stored as amplitudes, and a measurement returns only one outcome",
         ["The QFT's output is classical", "The QFT is slower than the FFT", "The QFT destroys its input"],
         "The coefficients live in amplitudes, so the QFT is useful as a subroutine (as in phase estimation), not as a faster FFT."),
    ]),
    "qml-36-quantum-phase-estimation": ("quantum-machine-learning", [
        ("What QPE estimates", "easy",
         "Quantum phase estimation estimates…",
         "The eigenphase φ in U|u⟩ = e^(2πiφ)|u⟩ for an eigenvector |u⟩ of a unitary U",
         ["The number of qubits", "The measurement basis", "The global phase of any state"],
         "QPE writes an eigenvalue's phase onto an ancilla register, turning eigenvalue problems into measurements."),
        ("Readout subroutine", "medium",
         "Which subroutine does QPE use at the end to read out the phase?",
         "The inverse quantum Fourier transform",
         ["Grover's diffusion operator", "The swap test", "Amplitude encoding"],
         "Controlled powers of U imprint the phase in the Fourier basis, and the inverse QFT converts it into a readable binary number."),
        ("Precision", "medium",
         "Adding more ancilla (counting) qubits in QPE…",
         "Increases the precision of the estimated phase",
         ["Decreases the precision", "Changes the eigenvalue", "Has no effect"],
         "Each extra counting qubit adds one more binary digit of precision to the phase."),
    ]),
    "qml-37-overview-of-the-hhl-algorithm": ("quantum-machine-learning", [
        ("HHL's problem", "easy",
         "What problem does the HHL algorithm address?",
         "Solving a linear system Ax = b",
         ["Factoring integers", "Searching an unsorted list", "Sorting numbers"],
         "HHL — Harrow, Hassidim and Lloyd — prepares a quantum state proportional to the solution of Ax = b."),
        ("HHL's output", "medium",
         "What does HHL actually output?",
         "A quantum state proportional to the solution vector x, not x itself",
         ["The full classical vector x", "Only the determinant of A", "A yes/no answer"],
         "Reading out all of x would take many repetitions, so HHL helps when you need only properties of x."),
        ("Caveats", "hard",
         "Which is a key caveat on HHL's exponential speed-up?",
         "It needs efficient state preparation, a sparse and well-conditioned A, and only properties of x as output",
         ["It has no caveats", "It only runs on classical computers", "It requires A to be the identity"],
         "Loading b, the condition number of A, and reading out results can each remove the advantage."),
    ]),
    "qml-38-quantum-matrix-inversion": ("quantum-machine-learning", [
        ("Reciprocal eigenvalues", "easy",
         "In HHL's inversion step, each eigencomponent is weighted by…",
         "1/λ, its reciprocal eigenvalue, applied through a controlled rotation",
         ["λ²", "λ", "e^λ"],
         "Inverting A means dividing each eigencomponent by its eigenvalue, done via an ancilla rotation."),
        ("Probabilistic success", "medium",
         "Why is the inversion step probabilistic?",
         "The ancilla must be measured in the right state, which can happen with low probability",
         ["Quantum computers are inherently random", "The eigenvalues are unknown", "The inverse does not exist"],
         "Post-selection on the ancilla succeeds only sometimes, which is why amplitude amplification is used."),
        ("Condition number", "medium",
         "How does the condition number κ of A affect HHL?",
         "A larger κ makes the algorithm slower — its runtime grows with κ",
         ["κ has no effect", "A larger κ makes it faster", "κ must be exactly 0"],
         "Small eigenvalues make 1/λ large and the post-selection unlikely, so ill-conditioned systems are costly."),
    ]),
    "qml-39-using-quantum-linear-algebra-for-learning": ("quantum-machine-learning", [
        ("Applications", "easy",
         "Which learning tasks has quantum linear algebra been applied to?",
         "Regression, principal component analysis and support vector machines",
         ["Only image generation", "Only sorting", "Only reinforcement learning without data"],
         "These methods reduce to linear algebra on large matrices, where HHL-style subroutines could help."),
        ("Checking claims", "medium",
         "Why must advertised quantum speed-ups for learning be checked carefully?",
         "Loading data and reading out results can erase the theoretical advantage",
         ["Speed-ups are always guaranteed", "Classical computers cannot do linear algebra", "They only apply to one-dimensional data"],
         "The input and output steps are often assumed free, but in practice they can dominate the cost."),
        ("Dequantisation", "hard",
         "What did 'dequantisation' results show about some quantum ML algorithms?",
         "Classical algorithms with similar sampling access can match their speed-ups",
         ["They run faster on real hardware", "They are impossible to simulate", "Quantum computers cannot run them"],
         "Given comparable data-access assumptions, classical sampling algorithms matched several claimed exponential speed-ups."),
    ]),
    "qml-40-quantum-assisted-gaussian-processes": ("quantum-machine-learning", [
        ("GP bottleneck", "easy",
         "What is the computational bottleneck in exact Gaussian process regression?",
         "Inverting the N×N kernel matrix, which costs O(N³) classically",
         ["Computing the mean", "Sorting the data", "Choosing a random seed"],
         "The cubic cost of inverting the kernel matrix limits exact Gaussian processes to modest datasets."),
        ("Quantum assistance", "medium",
         "How can quantum linear algebra help Gaussian processes?",
         "By using HHL-style subroutines for the kernel-matrix inversion",
         ["By removing the kernel entirely", "By measuring each data point", "By replacing the model with a decision tree"],
         "The expensive inversion is exactly the step quantum linear-algebra subroutines target."),
        ("GP predictions", "easy",
         "A Gaussian process predicts…",
         "A mean and an uncertainty (variance) for each new input",
         ["Only a class label", "A single number with no uncertainty", "A decision tree"],
         "Built-in uncertainty estimates are one of the main reasons to use Gaussian processes."),
    ]),
    "qml-41-guest-lecture-by-seth-lloyd": ("quantum-machine-learning", [
        ("Where QML helps", "easy",
         "Which is a realistic view of where quantum machine learning's opportunities lie?",
         "In problems with natively quantum data or structure, rather than any classical dataset",
         ["Exponentially speeding up every classical ML algorithm", "Replacing all classical computers today", "Removing the need for data"],
         "The strongest cases involve data that is already quantum, such as outputs of quantum experiments or simulations."),
        ("Lloyd's algorithm", "medium",
         "Seth Lloyd co-authored which well-known quantum algorithm?",
         "HHL, for solving linear systems",
         ["Shor's factoring algorithm", "Grover's search algorithm", "The Deutsch–Jozsa algorithm"],
         "HHL is named for Harrow, Hassidim and Lloyd, who introduced it in 2009."),
        ("Readout bottleneck", "medium",
         "Why is reading out results a recurring bottleneck in quantum machine learning?",
         "Each measurement gives one sample, so extracting a full vector can take exponentially many runs",
         ["Quantum results are already classical bits", "Readout is instant and exact", "Measurement adds information to the state"],
         "Measurement collapses the state to one outcome, so learning many amplitudes needs many repetitions."),
    ]),
    # ---- core topics whose only seeded questions were non-MCQ (match, fill-blank, ...),
    # ---- so the multiple-choice-only sprint quiz had nothing to draw from for them.
    "unitary-hermitian-matrices": ("quantum-computing", [
        ("Hermitian matrices", "easy",
         "A matrix H is Hermitian when…",
         "H = H†, it equals its own conjugate transpose",
         ["H†H = I", "H² = 0", "All its entries are real and positive"],
         "Hermitian means self-adjoint (H = H†), which guarantees real eigenvalues. H†H = I defines unitary instead."),
        ("Why gates are unitary", "medium",
         "Why must quantum gates be unitary?",
         "They must preserve the state's norm so probabilities still sum to 1",
         ["So that their eigenvalues are real", "So that they can be measured", "So that they commute with each other"],
         "Unitary operations are exactly the norm-preserving ones, and they are also reversible."),
        ("Pauli matrices", "medium",
         "The Pauli X, Y and Z matrices are…",
         "Both unitary and Hermitian",
         ["Unitary but not Hermitian", "Hermitian but not unitary", "Neither unitary nor Hermitian"],
         "Each Pauli matrix equals its own conjugate transpose and squares to I, so it is both Hermitian and unitary."),
    ]),
    "qubits-bloch-sphere": ("quantum-computing", [
        ("Bloch poles", "easy",
         "Where are |0⟩ and |1⟩ on the Bloch sphere?",
         "At the north and south poles",
         ["Both on the equator", "At the centre", "At the same point"],
         "The z-axis runs from |0⟩ at the north pole to |1⟩ at the south pole."),
        ("Equator states", "medium",
         "Where does |+⟩ = (|0⟩ + |1⟩)/√2 sit on the Bloch sphere?",
         "On the equator, along the +x axis",
         ["At the north pole", "At the centre of the sphere", "Along the −z axis"],
         "Equal superpositions lie on the equator; the relative phase sets the direction, and phase 0 points along +x."),
        ("Inside the sphere", "medium",
         "What do points strictly inside the Bloch sphere, rather than on its surface, represent?",
         "Mixed states",
         ["Pure states", "Invalid states that cannot exist", "Entangled two-qubit states"],
         "Pure states sit on the surface; mixed states fill the interior, with the maximally mixed state I/2 at the centre."),
    ]),
    "quantum-gates-circuits": ("quantum-computing", [
        ("Hadamard gate", "easy",
         "What does the Hadamard gate do to |0⟩?",
         "It produces (|0⟩ + |1⟩)/√2",
         ["It produces |1⟩", "It leaves it unchanged", "It produces −|0⟩"],
         "H maps |0⟩ to |+⟩ and |1⟩ to |−⟩, creating an equal superposition."),
        ("CNOT gate", "medium",
         "What does a CNOT gate do?",
         "Flips the target qubit if and only if the control qubit is |1⟩",
         ["Flips both qubits every time", "Measures the control qubit", "Swaps the two qubits"],
         "CNOT is the standard entangling gate: it applies X to the target conditioned on the control."),
        ("Z gate", "medium",
         "Which gate leaves |0⟩ unchanged and multiplies |1⟩ by −1?",
         "Z",
         ["X", "H", "CNOT"],
         "Z is a phase flip: it adds a relative phase of π between |0⟩ and |1⟩."),
    ]),
    "qiskit-programming": ("quantum-computing", [
        ("Building circuits", "easy",
         "In Qiskit, which object do you add gates to in order to build a circuit?",
         "QuantumCircuit",
         ["Statevector", "Backend", "Counts"],
         "You create a QuantumCircuit and call methods such as qc.h(0) and qc.cx(0, 1) to add gates."),
        ("qc.cx arguments", "medium",
         "In Qiskit, what does qc.cx(0, 1) apply?",
         "A CNOT with qubit 0 as control and qubit 1 as target",
         ["A CNOT with qubit 1 as control and qubit 0 as target", "An X gate on both qubits", "A swap of qubits 0 and 1"],
         "cx takes the control qubit first and the target second."),
        ("Why measure", "medium",
         "Why must a Qiskit circuit include measurements to get counts back from a simulator?",
         "Counts are built from measurement results written into classical bits",
         ["Gates cannot run without a measurement", "Measurement initialises the qubits", "Qiskit refuses to transpile circuits without one"],
         "Without measure() there are no classical outcomes to tally, so a counts-based result has nothing to report."),
    ]),
    "entanglement-bell-states": ("quantum-computing", [
        ("Preparing a Bell state", "easy",
         "Starting from |00⟩, which circuit prepares (|00⟩ + |11⟩)/√2?",
         "H on the first qubit, then CNOT from the first qubit to the second",
         ["CNOT first, then H on the second qubit", "X on both qubits", "H on both qubits and nothing else"],
         "H creates (|0⟩ + |1⟩)/√2 on the first qubit, and the CNOT copies that choice onto the second, entangling them."),
        ("Correlated outcomes", "medium",
         "Measuring the first qubit of (|00⟩ + |11⟩)/√2 gives 0. What will measuring the second qubit give?",
         "0, with certainty",
         ["1, with certainty", "0 or 1 with equal probability", "Nothing — the second qubit was destroyed"],
         "In this Bell state the two outcomes are perfectly correlated, so the first result fixes the second."),
        ("Bell basis", "medium",
         "How many Bell states form an orthonormal basis for two qubits?",
         "4",
         ["2", "3", "8"],
         "The four Bell states span the 4-dimensional two-qubit space, just like |00⟩, |01⟩, |10⟩ and |11⟩."),
    ]),
    "shors-factoring-algorithm": ("quantum-computing", [
        ("What Shor solves", "easy",
         "Which problem does Shor's algorithm solve efficiently?",
         "Factoring large integers",
         ["Searching an unsorted database", "Sorting lists", "Solving linear systems"],
         "Shor's algorithm factors integers in polynomial time, far faster than the best known classical methods."),
        ("Period finding", "medium",
         "Shor's algorithm reduces factoring to…",
         "Finding the period of modular exponentiation, using the quantum Fourier transform",
         ["A Grover search over all possible factors", "Solving a system of linear equations", "Measuring random qubits until a factor appears"],
         "Once the period of a^x mod N is known, classical number theory turns it into a factor of N."),
        ("Security impact", "medium",
         "Why does Shor's algorithm matter for cybersecurity?",
         "It would break RSA encryption, whose security relies on factoring being hard",
         ["It speeds up password hashing", "It makes all encryption unbreakable", "It mainly threatens symmetric ciphers such as AES"],
         "RSA's security rests on factoring being intractable; a large quantum computer running Shor's algorithm would remove that."),
    ]),
}


GAP_QUESTIONS: List[Dict[str, Any]] = [
    _mcq(slug, domain_tag, question)
    for slug, (domain_tag, questions) in QUESTIONS_BY_TOPIC.items()
    for question in questions
]
