import React, { useState } from 'react';
import type { LearningSummaryReport } from '../types/analytics.types';
import { sendAnalyticsReportEmail } from '../api';
import { useTheme } from '@/context/ThemeContext';
import { useAuth } from '@/context/AuthContext';
import { cn } from '@/lib/utils';
import { motion } from 'framer-motion';
import { FaFileDownload, FaClipboardList, FaCheckCircle, FaEnvelope, FaSpinner } from 'react-icons/fa';
import jsPDF from 'jspdf';
import { toast } from 'sonner';

interface AnalyticsSummaryReportProps {
  summary: LearningSummaryReport;
  studentName?: string;
}

export const AnalyticsSummaryReport: React.FC<AnalyticsSummaryReportProps> = ({ summary, studentName = 'Quantum Learner' }) => {
  const { theme } = useTheme();
  const { currentUser } = useAuth();
  const [sendingEmail, setSendingEmail] = useState(false);

  const handleSendEmail = async () => {
    setSendingEmail(true);
    try {
      const emailToUse = currentUser?.email || undefined;
      const res = await sendAnalyticsReportEmail(emailToUse);
      const targetEmail = res.data?.to_email || emailToUse || 'your registered email';
      toast.success(`Academic Progress Report successfully emailed to ${targetEmail}!`);
    } catch (err: any) {
      console.error("Failed to email report:", err);
      toast.error(err?.response?.data?.detail || "Failed to send progress report email.");
    } finally {
      setSendingEmail(false);
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      
      // Page styling
      doc.setFillColor(250, 250, 250);
      doc.rect(0, 0, 210, 297, 'F');

      // Decorative Header Bar
      doc.setFillColor(16, 185, 129); // Emerald 500
      doc.rect(0, 0, 210, 16, 'F');

      // Title Section
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(24, 24, 27);
      doc.text("Qrious Quantum Platform", 20, 32);

      doc.setFontSize(14);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(113, 113, 122);
      doc.text("Official Academic Learning Progress Report", 20, 40);

      // Divider Line
      doc.setDrawColor(228, 228, 231);
      doc.setLineWidth(0.5);
      doc.line(20, 46, 190, 46);

      // Student Meta Box
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(24, 24, 27);
      doc.text(`Student Name: ${studentName}`, 20, 56);
      doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 130, 56);

      // Metrics Summary Table
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(20, 64, 170, 70, 3, 3, 'FD');

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(16, 185, 129);
      doc.text("Key Performance Metrics", 28, 74);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(39, 39, 42);

      doc.text(`Overall Accuracy: ${summary.overall_accuracy_pct}%`, 28, 86);
      doc.text(`Learning Gain: ${summary.learning_gain_text}`, 28, 96);
      doc.text(`Study Consistency: ${summary.study_consistency}`, 28, 106);

      doc.text(`Strongest Area: ${summary.strongest_area}`, 110, 86);
      doc.text(`Focus Area: ${summary.focus_area}`, 110, 96);

      // Recommendation Box
      doc.setFillColor(236, 253, 245);
      doc.roundedRect(20, 142, 170, 36, 3, 3, 'FD');

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(6, 95, 70);
      doc.text("Academic Recommendation", 28, 152);

      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(4, 120, 87);
      const splitText = doc.splitTextToSize(summary.recommendation_text, 154);
      doc.text(splitText, 28, 160);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(161, 161, 170);
      doc.text("Generated by Qrious AI Quantum Learning Platform • Verified Academic Record", 105, 280, { align: 'center' });

      doc.save(`Qrious_Academic_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
      toast.success("Academic Progress Report PDF downloaded successfully!");
    } catch (err) {
      console.error("PDF generation failed:", err);
      toast.error("Failed to generate PDF report.");
    }
  };

  return (
    <motion.div
      className={cn(
        "p-8 rounded-[2rem] border overflow-hidden shadow-sm flex flex-col justify-between h-full font-sans transition-all duration-300",
        theme === 'dark' ? "bg-zinc-950/50 border-white/10" : "bg-white border-zinc-200"
      )}
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-50px" }}
      transition={{ duration: 0.5 }}
    >
      <div>
        {/* Header */}
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6">
          <div className="flex items-center gap-3">
            <div className={cn(
              "w-10 h-10 rounded-xl flex items-center justify-center border shadow-sm",
              theme === 'dark' ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400" : "bg-emerald-50 border-emerald-200 text-emerald-600"
            )}>
              <FaClipboardList className="text-lg" />
            </div>
            <div>
              <h3 className="text-xl font-medium tracking-tight">Analytics Summary Report</h3>
              <p className={cn("text-xs mt-0.5", theme === 'dark' ? "text-zinc-400" : "text-zinc-600")}>
                Official evidence-based academic transcript summary
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-2.5">
            <button
              onClick={handleSendEmail}
              disabled={sendingEmail}
              className="px-4 py-2.5 bg-emerald-500 text-white rounded-xl shadow hover:bg-emerald-600 font-medium text-xs transition-all duration-200 flex items-center justify-center gap-2 shrink-0 disabled:opacity-50 cursor-pointer"
            >
              {sendingEmail ? <FaSpinner className="animate-spin text-sm" /> : <FaEnvelope className="text-sm" />}
              <span>{sendingEmail ? "Emailing Report..." : "Email Report"}</span>
            </button>

            <button
              onClick={handleDownloadPDF}
              className={cn(
                "px-4 py-2.5 rounded-xl border font-medium text-xs transition-all duration-200 flex items-center justify-center gap-2 shrink-0 cursor-pointer",
                theme === 'dark'
                  ? "bg-zinc-900 border-white/10 text-zinc-200 hover:bg-black hover:border-emerald-500/40"
                  : "bg-zinc-100 border-zinc-200 text-zinc-800 hover:bg-zinc-200/80 hover:border-emerald-500/40"
              )}
            >
              <FaFileDownload className="text-sm text-emerald-500" />
              <span>Download PDF</span>
            </button>
          </div>
        </div>

        {/* Structured Summary Table */}
        <div className={cn(
          "p-6 rounded-2xl border mb-6 grid grid-cols-2 md:grid-cols-3 gap-6 font-mono text-xs",
          theme === 'dark' ? "bg-zinc-900/40 border-white/10" : "bg-zinc-50 border-zinc-200"
        )}>
          <div>
            <span className={cn("block uppercase text-[10px]", theme === 'dark' ? "text-zinc-500" : "text-zinc-400")}>Overall Accuracy</span>
            <span className="text-xl font-extrabold text-emerald-500 mt-1 block">{summary.overall_accuracy_pct}%</span>
          </div>

          <div>
            <span className={cn("block uppercase text-[10px]", theme === 'dark' ? "text-zinc-500" : "text-zinc-400")}>Learning Gain</span>
            <span className="text-xl font-extrabold text-emerald-500 mt-1 block">{summary.learning_gain_text}</span>
          </div>

          <div>
            <span className={cn("block uppercase text-[10px]", theme === 'dark' ? "text-zinc-500" : "text-zinc-400")}>Study Consistency</span>
            <span className="text-xl font-extrabold text-foreground mt-1 block">{summary.study_consistency}</span>
          </div>

          <div>
            <span className={cn("block uppercase text-[10px]", theme === 'dark' ? "text-zinc-500" : "text-zinc-400")}>Strongest Area</span>
            <span className="text-sm font-medium text-foreground mt-1 block font-sans truncate">{summary.strongest_area}</span>
          </div>

          <div className="col-span-2">
            <span className={cn("block uppercase text-[10px]", theme === 'dark' ? "text-zinc-500" : "text-zinc-400")}>Focus Area</span>
            <span className="text-sm font-medium text-amber-500 mt-1 block font-sans truncate">{summary.focus_area}</span>
          </div>
        </div>

        {/* Recommendation Statement */}
        <div className={cn(
          "p-4 rounded-xl border text-xs font-sans leading-relaxed flex items-center gap-3",
          theme === 'dark' ? "bg-zinc-900/60 border-white/10 text-zinc-300" : "bg-zinc-100 border-zinc-200 text-zinc-700"
        )}>
          <FaCheckCircle className="text-emerald-500 shrink-0 text-base" />
          <div>
            <span className="font-semibold text-foreground mr-2">Recommendation:</span>
            {summary.recommendation_text}
          </div>
        </div>
      </div>
    </motion.div>
  );
};
